package com.tn.isamm.linkedin.entity;
// Generated Oct 21, 2018 10:21:03 AM by Hibernate Tools 4.3.1


import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;

import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name="commentaire"
    ,catalog="linkedin2"
)
public class Commentaire  implements java.io.Serializable {


     private Integer id;
     private int publication;
     private Utilisateur utilisateur;
     private String contenu;
     private Date date;

    public Commentaire() {
    }

    public Commentaire(Integer id, int publication, Utilisateur utilisateur, String contenu, Date date) {
        this.id = id;
        this.publication = publication;
        this.utilisateur = utilisateur;
        this.contenu = contenu;
        this.date = date;
    }

    @Id
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @JoinColumn(name="id_publication", nullable=false)
    public int getPublication() {
        return this.publication;
    }
    
    public void setPublication(int publication) {
        this.publication = publication;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_utilisateur", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="contenu", nullable=false, length=16777215)
    public String getContenu() {return contenu;}

    public void setContenu(String contenu) {this.contenu = contenu;}

    @UpdateTimestamp
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19, updatable=false)
    public Date getDate() {return date;}

    public void setDate(Date date) {this.date = date;}
}


