package com.tn.isamm.linkedin.entity;
// Generated Oct 21, 2018 10:21:03 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;


/**
 * Competence generated by hbm2java
 */
@Entity
@Table(name="competence"
    ,catalog="linkedin2"
)
public class Competence  implements java.io.Serializable {


     private Integer id;
     private Utilisateur utilisateur;
     private String nomCompetence;

    public Competence() {
    }

    public Competence(Utilisateur utilisateur, String nomCompetence) {
       this.utilisateur = utilisateur;
       this.nomCompetence = nomCompetence;
    }


    @Id @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    public void setId(Integer id) {
        this.id = id;
    }



    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_utilisateur", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="nom_competence",  length=10000)
    public String getNomCompetence() {
        return this.nomCompetence;
    }
    public void setNomCompetence(String nomCompetence) {
        this.nomCompetence = nomCompetence;
    }
}


