package com.tn.isamm.linkedin.entity;
// Generated Oct 21, 2018 10:21:03 AM by Hibernate Tools 4.3.1


import java.util.*;
import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;


/**
 * Formation generated by hbm2java
 */
@Entity
@Table(name="formation"
    ,catalog="linkedin2"
)
public class Formation  implements java.io.Serializable {


     private Integer id;
     private Utilisateur utilisateur;
     private String ecole;
     private String diplome;
     private Date dateDebut;
     private Date dateFin;
     private String discipline;
    private String description;

    public Formation() {
    }

    public Formation(Utilisateur utilisateur, String ecole, String diplome, Date dateDebut, Date dateFin, String discipline,String description) {
       this.utilisateur = utilisateur;
       this.ecole = ecole;
       this.diplome = diplome;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.discipline = discipline;
       this.description=description;
    }
   
    @Id @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    public void setId(Integer id) {
        this.id = id;
    }


    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_utilisateur", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="ecole",  length=1000)
    public String getEcole() {
        return this.ecole;
    }
    public void setEcole(String ecole) {
        this.ecole = ecole;
    }

    
    @Column(name="diplome",  length=1000)
    public String getDiplome() {
        return this.diplome;
    }
    public void setDiplome(String diplome) {
        this.diplome = diplome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_debut",  length=10)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_fin",  length=10)
    public Date getDateFin() {
        return this.dateFin;
    }
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="discipline",  length=1000)
    public String getDiscipline() {
        return this.discipline;
    }
    public void setDiscipline(String discipline) {
        this.discipline = discipline;
    }

    @Column(name="description",  length=1000)
    public String getDescription() {
        return this.description;
    }
    public void setDescription(String description) {
        this.description = description;
    }




}


