package com.tn.isamm.linkedin.entity;
// Generated Oct 21, 2018 10:21:03 AM by Hibernate Tools 4.3.1


import java.util.*;
import javax.persistence.*;

/**
 * JAime generated by hbm2java
 */
@Entity
@Table(name="j_aime"
    ,catalog="linkedin2"
)
public class JAime  implements java.io.Serializable {


     private Integer id;
     private int publication;
     private Utilisateur utilisateur;
     private Date date;

    public JAime() {
    }

    public JAime(Integer id, int publication, Utilisateur utilisateur, Date date) {
       this.id = id;
       this.publication = publication;
       this.utilisateur = utilisateur;
       this.date = date;
    }

    @Id
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @JoinColumn(name="id_publication", nullable=false, updatable=false)
    public int getPublication() {
        return this.publication;
    }
    
    public void setPublication(int publication) {
        this.publication = publication;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_utilisateur", nullable=false,  updatable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


