package com.tn.isamm.linkedin.entity;
// Generated Oct 21, 2018 10:21:03 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import static javax.persistence.GenerationType.IDENTITY;


/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
    ,catalog="linkedin2"
)
public class Message  implements java.io.Serializable {


     private Integer id;
     private Utilisateur utilisateurByIdEnvoyeur;
     private Utilisateur utilisateurByIdDestinataire;
     private String contenuTx;

    public Message() {
    }

    public Message(Utilisateur utilisateurByIdEnvoyeur, Utilisateur utilisateurByIdDestinataire, String contenuTx) {
       this.utilisateurByIdEnvoyeur = utilisateurByIdEnvoyeur;
       this.utilisateurByIdDestinataire = utilisateurByIdDestinataire;
       this.contenuTx = contenuTx;
    }
   
     @Id
     @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_envoyeur", nullable=false)
    public Utilisateur getUtilisateurByIdEnvoyeur() {
        return this.utilisateurByIdEnvoyeur;
    }
    
    public void setUtilisateurByIdEnvoyeur(Utilisateur utilisateurByIdEnvoyeur) {
        this.utilisateurByIdEnvoyeur = utilisateurByIdEnvoyeur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_destinataire", nullable=false)
    public Utilisateur getUtilisateurByIdDestinataire() {
        return this.utilisateurByIdDestinataire;
    }
    
    public void setUtilisateurByIdDestinataire(Utilisateur utilisateurByIdDestinataire) {
        this.utilisateurByIdDestinataire = utilisateurByIdDestinataire;
    }

    
    @Column(name="contenu_tx", nullable=false, length=200)
    public String getContenuTx() {
        return this.contenuTx;
    }
    
    public void setContenuTx(String contenuTx) {
        this.contenuTx = contenuTx;
    }




}


