package com.tn.isamm.linkedin.entity;
// Generated Nov 18, 2018 11:58:56 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name="notification"
    ,catalog="linkedin2"
)
public class Notification  implements java.io.Serializable {


    private Integer id;
    private Utilisateur utilisateur;
    private Utilisateur utilisateur1;
    private Date date;
    private String lien;
    private String objet;

    public Notification() {
    }

    public Notification(Utilisateur utilisateur, Date date, String lien, String objet) {
        this.utilisateur = utilisateur;
        this.date = date;
        this.lien = lien;
        this.objet = objet;
    }

    @Id
    @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_recepteur", nullable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_envoi", nullable=false)
    public Utilisateur getUtilisateur1() {
        return this.utilisateur1;
    }

    public void setUtilisateur1(Utilisateur utilisateur1) {
        this.utilisateur1 = utilisateur1;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }


    @Column(name="lien", nullable=false, length=200)
    public String getLien() {
        return this.lien;
    }

    public void setLien(String lien) {
        this.lien = lien;
    }


    @Column(name="objet", nullable=false, length=300)
    public String getObjet() {
        return this.objet;
    }

    public void setObjet(String objet) {
        this.objet = objet;
    }




}