package com.tn.isamm.linkedin.entity;
// Generated Oct 21, 2018 10:21:03 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonManagedReference;

import javax.persistence.*;

/**
 * OffreUtilisateur generated by hbm2java
 */
@Entity
@Table(name="offre_utilisateur"
    ,catalog="linkedin2"
)
public class OffreUtilisateur  implements java.io.Serializable {


     private OffreUtilisateurId id;
     private OffreEmploi offreEmploi;
     private Utilisateur utilisateur;

    public OffreUtilisateur() {
    }

    public OffreUtilisateur(OffreUtilisateurId id, OffreEmploi offreEmploi, Utilisateur utilisateur) {
       this.id = id;
       this.offreEmploi = offreEmploi;
       this.utilisateur = utilisateur;
    }

     @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="idOffre", column=@Column(name="id_offre", nullable=false) ),
        @AttributeOverride(name="idUser", column=@Column(name="id_user", nullable=false) ),
        @AttributeOverride(name="date", column=@Column(name="date", length=19) ) } )
    public OffreUtilisateurId getId() {
        return this.id;
    }

    public void setId(OffreUtilisateurId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_offre", nullable=false, insertable=false, updatable=false)
    public OffreEmploi getOffreEmploi() {
        return this.offreEmploi;
    }

    public void setOffreEmploi(OffreEmploi offreEmploi) {
        this.offreEmploi = offreEmploi;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_user", nullable=false, insertable=false, updatable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }




}


