package com.tn.isamm.linkedin.entity;
// Generated Oct 21, 2018 10:21:03 AM by Hibernate Tools 4.3.1


import java.util.*;
import javax.persistence.*;

/**
 * OffreUtilisateurId generated by hbm2java
 */
@Embeddable
public class OffreUtilisateurId  implements java.io.Serializable {


    private int idOffre;
    private int idUser;
    private Date date;


    public OffreUtilisateurId() {
    }

    public OffreUtilisateurId(int idOffre, int idUser, Date date) {
       this.idOffre = idOffre;
       this.idUser = idUser;
       this.date = date;
    }



    @Column(name="id_offre", nullable=false)
    public int getIdOffre() {
        return this.idOffre;
    }

    public void setIdOffre(int idOffre) {
        this.idOffre = idOffre;
    }


    @Column(name="id_user", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OffreUtilisateurId) ) return false;
		 OffreUtilisateurId castOther = ( OffreUtilisateurId ) other;

		 return (this.getIdOffre()==castOther.getIdOffre())
 && (this.getIdUser()==castOther.getIdUser())
 && ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;

         result = 37 * result + this.getIdOffre();
         result = 37 * result + this.getIdUser();
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         return result;
   }


}


